### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=GoLand

###

### Auth
POST localhost:8081/api/auth
Content-Type: application/json

{
  "username": "Nic",
  "Password": "12345"
}

### Get info
GET localhost:8081/api/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxfQ.jYyRJbb0WImFoUUdcslQQfwnXTHJzne-6tsPd8Hrw0I
Content-Type: application/json

### Buy item
GET localhost:8081/api/buy/umbrella
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxfQ.jYyRJbb0WImFoUUdcslQQfwnXTHJzne-6tsPd8Hrw0I
Content-Type: application/json

### Send Coin
POST localhost:8081/api/sendCoin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0fQ.nx7SmIYqAtbOD7Co5dT1QFDS-K90Fw8LPdZebt9KGUg
Content-Type: application/json

{
  "toUser": "John",
  "amount": 1500
}